version: '3.8'
services:

  frontend:
    restart: always
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true


  db:
    environment:
      POSTGRES_USER: dbadm
      POSTGRES_PASSWORD: dbpwd
      POSTGRES_DB: db
      POSTGRES_HOST_AUTH_METHOD: trust
    image: postgres:12.2
    networks:
      - postgres-compose-network
    ports:
      - 5405:5432
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  api:
    build: ./api
    depends_on:
      - db
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://dbadm:dbpwd@db:5405/db    
    networks:
      - postgres-compose-network
    ports:
      - '5050:5050'
    volumes:
      - ./api:/app
      - ./migrations:/usr/src/app/migrations
    restart: always

  db-pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "yurilemos98@hotmail.com"
      PGADMIN_DEFAULT_PASSWORD: dbpwd
    ports:
      - "16543:80"
    depends_on:
      - db
    networks:
      - postgres-compose-network

  

  


volumes:
  dbdata:

networks: 
  postgres-compose-network:
    driver: bridge
