"""empty message

Revision ID: 1f67e79b7187
Revises: 5d8fcbda1172
Create Date: 2022-10-19 21:52:31.060492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f67e79b7187'
down_revision = '5d8fcbda1172'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('avatar', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'avatar')
    # ### end Alembic commands ###
