"""empty message

Revision ID: 855be51033e8
Revises: b32bd17002de
Create Date: 2022-09-17 11:32:46.481996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '855be51033e8'
down_revision = 'b32bd17002de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fala', sa.Column('nome_usuario', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fala', 'nome_usuario')
    # ### end Alembic commands ###
