"""empty message

Revision ID: f7aa2aa2669b
Revises: 6cc7251848cd
Create Date: 2022-09-18 14:36:02.010325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7aa2aa2669b'
down_revision = '6cc7251848cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('assunto_discussao_id_fkey', 'assunto', type_='foreignkey')
    op.drop_constraint('assunto_usuario_id_fkey', 'assunto', type_='foreignkey')
    op.create_foreign_key(None, 'assunto', 'usuario', ['usuario_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'assunto', 'discussao', ['discussao_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('customização_usuario_id_fkey', 'customização', type_='foreignkey')
    op.drop_constraint('customização_customizacao_padrao_id_fkey', 'customização', type_='foreignkey')
    op.create_foreign_key(None, 'customização', 'grupo', ['usuario_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'customização', 'customização_padrao', ['customizacao_padrao_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('discussao_usuario_id_fkey', 'discussao', type_='foreignkey')
    op.drop_constraint('discussao_grupo_id_fkey', 'discussao', type_='foreignkey')
    op.create_foreign_key(None, 'discussao', 'grupo', ['grupo_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'discussao', 'usuario', ['usuario_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.alter_column('fala', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('fala_fala_mae_id_fkey', 'fala', type_='foreignkey')
    op.drop_constraint('fala_assunto_id_fkey', 'fala', type_='foreignkey')
    op.drop_constraint('fala_usuario_id_fkey', 'fala', type_='foreignkey')
    op.drop_constraint('fala_relacao_id_fkey', 'fala', type_='foreignkey')
    op.create_foreign_key(None, 'fala', 'fala', ['fala_mae_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'fala', 'assunto', ['assunto_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'fala', 'usuario', ['usuario_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'fala', 'relacao', ['relacao_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('grupo_usuario_id_fkey', 'grupo', type_='foreignkey')
    op.create_foreign_key(None, 'grupo', 'usuario', ['usuario_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_constraint('participacao_usuario_id_fkey', 'participacao', type_='foreignkey')
    op.drop_constraint('participacao_grupo_id_fkey', 'participacao', type_='foreignkey')
    op.create_foreign_key(None, 'participacao', 'usuario', ['usuario_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'participacao', 'grupo', ['grupo_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('relacao_classe_relacao_id_fkey', 'relacao', type_='foreignkey')
    op.create_foreign_key(None, 'relacao', 'classe_relacao', ['classe_relacao_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('relacao_fala_relacao_id_fkey', 'relacao_fala', type_='foreignkey')
    op.create_foreign_key(None, 'relacao_fala', 'relacao', ['relacao_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'relacao_fala', type_='foreignkey')
    op.create_foreign_key('relacao_fala_relacao_id_fkey', 'relacao_fala', 'relacao', ['relacao_id'], ['id'])
    op.drop_constraint(None, 'relacao', type_='foreignkey')
    op.create_foreign_key('relacao_classe_relacao_id_fkey', 'relacao', 'classe_relacao', ['classe_relacao_id'], ['id'])
    op.drop_constraint(None, 'participacao', type_='foreignkey')
    op.drop_constraint(None, 'participacao', type_='foreignkey')
    op.create_foreign_key('participacao_grupo_id_fkey', 'participacao', 'grupo', ['grupo_id'], ['id'])
    op.create_foreign_key('participacao_usuario_id_fkey', 'participacao', 'usuario', ['usuario_id'], ['id'])
    op.drop_constraint(None, 'grupo', type_='foreignkey')
    op.create_foreign_key('grupo_usuario_id_fkey', 'grupo', 'usuario', ['usuario_id'], ['id'])
    op.drop_constraint(None, 'fala', type_='foreignkey')
    op.drop_constraint(None, 'fala', type_='foreignkey')
    op.drop_constraint(None, 'fala', type_='foreignkey')
    op.drop_constraint(None, 'fala', type_='foreignkey')
    op.create_foreign_key('fala_relacao_id_fkey', 'fala', 'relacao', ['relacao_id'], ['id'])
    op.create_foreign_key('fala_usuario_id_fkey', 'fala', 'usuario', ['usuario_id'], ['id'])
    op.create_foreign_key('fala_assunto_id_fkey', 'fala', 'assunto', ['assunto_id'], ['id'])
    op.create_foreign_key('fala_fala_mae_id_fkey', 'fala', 'fala', ['fala_mae_id'], ['id'])
    op.alter_column('fala', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'discussao', type_='foreignkey')
    op.drop_constraint(None, 'discussao', type_='foreignkey')
    op.create_foreign_key('discussao_grupo_id_fkey', 'discussao', 'grupo', ['grupo_id'], ['id'])
    op.create_foreign_key('discussao_usuario_id_fkey', 'discussao', 'usuario', ['usuario_id'], ['id'])
    op.drop_constraint(None, 'customização', type_='foreignkey')
    op.drop_constraint(None, 'customização', type_='foreignkey')
    op.create_foreign_key('customização_customizacao_padrao_id_fkey', 'customização', 'customização_padrao', ['customizacao_padrao_id'], ['id'])
    op.create_foreign_key('customização_usuario_id_fkey', 'customização', 'grupo', ['usuario_id'], ['id'])
    op.drop_constraint(None, 'assunto', type_='foreignkey')
    op.drop_constraint(None, 'assunto', type_='foreignkey')
    op.create_foreign_key('assunto_usuario_id_fkey', 'assunto', 'usuario', ['usuario_id'], ['id'])
    op.create_foreign_key('assunto_discussao_id_fkey', 'assunto', 'discussao', ['discussao_id'], ['id'])
    # ### end Alembic commands ###
