"""empty message

Revision ID: 5680f64a4d98
Revises: 
Create Date: 2022-07-13 16:38:47.139100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5680f64a4d98'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classe_relacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customização_padrao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=20), nullable=False),
    sa.Column('descricao', sa.String(length=50), nullable=True),
    sa.Column('valor', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=20), nullable=False),
    sa.Column('senha', sa.String(length=128), nullable=False),
    sa.Column('perfil_usuario', sa.String(length=20), nullable=False),
    sa.Column('email_usuario', sa.String(length=100), nullable=False),
    sa.Column('nome_usuario', sa.String(length=40), nullable=True),
    sa.Column('data_ult_visita_usuario', sa.DateTime(), nullable=True),
    sa.Column('data_pen_visita_usuario', sa.DateTime(), nullable=True),
    sa.Column('tags_usuario', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grupo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_grupo', sa.String(length=50), nullable=False),
    sa.Column('descricao_grupo', sa.Text(), nullable=True),
    sa.Column('data_criacao_grupo', sa.DateTime(), nullable=False),
    sa.Column('visibilidade_grupo', sa.SmallInteger(), nullable=True),
    sa.Column('status_grupo', sa.SmallInteger(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=True),
    sa.Column('classe_relacao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['classe_relacao_id'], ['classe_relacao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customização',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('customizacao_padrao_id', sa.Integer(), nullable=True),
    sa.Column('valor', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['customizacao_padrao_id'], ['customização_padrao.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['grupo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discussao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data_criacao_descricao', sa.DateTime(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupo.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['grupo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('grupo_id', sa.Integer(), nullable=True),
    sa.Column('nivel_participacao', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupo.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assunto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data_criacao_descricao', sa.DateTime(), nullable=False),
    sa.Column('data_ult_atualizacao', sa.DateTime(), nullable=True),
    sa.Column('discussao_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['discussao_id'], ['discussao.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['grupo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fala',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('data_criacao_fala', sa.DateTime(), nullable=False),
    sa.Column('data_ult_atualizacao_fala', sa.DateTime(), nullable=True),
    sa.Column('imagem_virtual', sa.String(length=256), nullable=True),
    sa.Column('imagem_real', sa.String(length=256), nullable=True),
    sa.Column('tamanho', sa.Integer(), nullable=True),
    sa.Column('arquivo_virtual', sa.String(length=256), nullable=True),
    sa.Column('arquivo_real', sa.String(length=256), nullable=True),
    sa.Column('arquivo_tamanho', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=256), nullable=True),
    sa.Column('assunto_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('relacao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assunto_id'], ['assunto.id'], ),
    sa.ForeignKeyConstraint(['relacao_id'], ['relacao.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relacao_fala',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fala_mae_id', sa.Integer(), nullable=True),
    sa.Column('relacao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fala_mae_id'], ['fala.id'], ),
    sa.ForeignKeyConstraint(['relacao_id'], ['relacao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relacao_fala')
    op.drop_table('fala')
    op.drop_table('assunto')
    op.drop_table('participacao')
    op.drop_table('discussao')
    op.drop_table('customização')
    op.drop_table('relacao')
    op.drop_table('grupo')
    op.drop_table('usuario')
    op.drop_table('customização_padrao')
    op.drop_table('classe_relacao')
    # ### end Alembic commands ###
