"""empty message

Revision ID: 8df6636607bc
Revises: a679139f63ae
Create Date: 2022-09-05 20:07:39.927136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8df6636607bc'
down_revision = 'a679139f63ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('discussao_usuario_id_fkey', 'discussao', type_='foreignkey')
    op.create_foreign_key(None, 'discussao', 'usuario', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'discussao', type_='foreignkey')
    op.create_foreign_key('discussao_usuario_id_fkey', 'discussao', 'grupo', ['usuario_id'], ['id'])
    # ### end Alembic commands ###
